name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compilar para Arduino Uno
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          # arduino-cli no trae LiquidCrystal preinstalada como el IDE
          libraries: |
            - name: LiquidCrystal
          sketch-paths: |
            - ./
          enable-warnings-report: true
          verbose: false
